In [1]:
import pandas as pd
import numpy as np
import re

In [34]:
df = pd.read_csv("./qgis_data/2019_전처리.csv", encoding = "euc-kr")
df["옐로카펫_"] = df["옐로카펫_"].str.replace("-", "")

In [47]:
weather = pd.read_csv("./기상정보_20100101-20191231.csv", encoding = "euc-kr")

In [48]:
weather["날짜"] = weather["날짜"].str.replace("-", "")

In [49]:
weather.head(1)

         날짜   지점  평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm)
0  20100101  108     -7.6    -12.7     -3.6      NaN

In [52]:
df = pd.merge(df, weather, left_on = "발생년월일", right_on="날짜", how = "inner")

In [95]:
df["옐로카펫_설치유무"] = 0

In [97]:
lst_idx = df["옐로카펫_"].dropna().index

for idx in lst_idx:
    if df.loc[idx, "옐로카펫_"] != "0":
        if df.loc[idx, "발생년월일"] > df.loc[idx, "옐로카펫_"]:
            df.loc[idx, "옐로카펫_설치유무"] = 1

6
20
23
44
54
63
94
98
152
156
202
285
297
301
315
324

In [82]:
df.head(10)

,발생년,발생년월일,주야,요일,사망자수,부상자수,중상자수,경상자수,부상신고자,발생지시도,...,제공기관명,옐로카펫_,보호구역_,날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃),강수량(mm),옐로카펫_설치유무
0,2019,20190102,주,수,1,0,0,0,0,서울,...,NaN,NaN,NaN,20190102,108,-4.9,-8.8,0.2,NaN,0
1,2019,20190103,주,목,1,1,0,1,0,서울,...,서울특별시 노원구,0,2.0,20190103,108,-3.5,-8.4,3.2,NaN,1
2,2019,20190103,주,목,1,0,0,0,0,서울,...,NaN,NaN,NaN,20190103,108,-3.5,-8.4,3.2,NaN,0
3,2019,20190108,야,화,1,0,0,0,0,서울,...,서울특별시 강서구,0,97.0,20190108,108,-3.5,-7.2,0.5,NaN,1
4,2019,20190114,주,월,1,0,0,0,0,서울,...,서울특별시 구로구,0,98.0,20190114,108,1.4,-2.4,5.3,NaN,1
5,2019,20190116,야,수,1,0,0,0,0,서울,...,서울특별시 성동구,0,97.0,20190116,108,-5.2,-10.1,-1.1,0.0,1
6,2019,20190116,야,수,1,0,0,0,0,서울,...,서울특별시 성동구,20171212,97.0,20190116,108,-5.2,-10.1,-1.1,0.0,1
7,2019,20190116,야,수,1,0,0,0,0,서울,...,NaN,NaN,NaN,20190116,108,-5.2,-10.1,-1.1,0.0,0
8,2019,20190117,야,목,1,0,0,0,0,서울,...,NaN,NaN,NaN,20190117,108,-0.3,-3.2,4.0,0.0,0
9,2019,20190117,주,목,1,4,2,2,0,서울,...,NaN,NaN,NaN,20190117,108,-0.3,-3.2,4.0,0.0,0

In [98]:
df.to_csv("./qgis_data/2019_전처리_기상정보.csv", encoding = "euc-kr", index = False)

In [107]:
df["발생년월일"]

0      20180214
1      20180214
2      20180214
3      20180214
4      20180214
         ...
117    20180214
118    20180214
119    20180214
120    20180214
121    20180214
Name: 발생년월일, Length: 122, dtype: int64

In [245]:
df = pd.read_csv("./qgis_data/2018.csv", encoding = "euc-kr")
df["옐로카펫_"] = df["옐로카펫_"].str.replace("-", "")
df["발생년월일"] = df["발생년월일"].astype(object)
df["평균기온(℃)"] = 0; df["최저기온(℃)"] = 0; df["최고기온(℃)"] = 0; df["강수량(mm)"] = 0

weather = pd.read_csv("./기상정보_20100101-20191231.csv", encoding = "euc-kr")

weather["날짜"] = weather["날짜"].str.replace("-", "")

for idx in range(len(df)):
    a = weather[weather["날짜"] == str(df.loc[idx, "발생년월일"])]

    df.iloc[idx, 39] = a.iloc[0, 2]
    df.iloc[idx, 40] = a.iloc[0, 3]
    df.iloc[idx, 41] = a.iloc[0, 4]
    df.iloc[idx, 42] = a.iloc[0, 5]

df["옐로카펫_설치유무"] = 0


lst_idx = df["옐로카펫_"].dropna().index

for idx in lst_idx:
    if df.loc[idx, "옐로카펫_"] != "0":
        if str(df.loc[idx, "발생년월일"]) > str(df.loc[idx, "옐로카펫_"]):
            df.loc[idx, "옐로카펫_설치유무"] = 1

In [246]:
df.to_csv("./qgis_data/2018_전처리_기상정보.csv", encoding = "euc-kr")

In [240]:
df2012 = pd.read_csv("./qgis_data/2012_전처리_기상정보.csv", encoding = "euc-kr")
df2013 = pd.read_csv("./qgis_data/2013_전처리_기상정보.csv", encoding = "euc-kr")
df2014 = pd.read_csv("./qgis_data/2014_전처리_기상정보.csv", encoding = "euc-kr")
df2015 = pd.read_csv("./qgis_data/2015_전처리_기상정보.csv", encoding = "euc-kr")
df2016 = pd.read_csv("./qgis_data/2016_전처리_기상정보.csv", encoding = "euc-kr")
df2017 = pd.read_csv("./qgis_data/2017_전처리_기상정보.csv", encoding = "euc-kr")
df2018 = pd.read_csv("./qgis_data/2018_전처리_기상정보.csv", encoding = "euc-kr")

In [241]:
df = pd.concat([df2012, df2013, df2014, df2015, df2016, df2017, df2018])

In [242]:
df.reset_index(drop = True, inplace = True)

In [243]:
df.to_csv("./qgis_data/without_2019_from_2018_to_2012.csv", index = False, encoding = "euc-kr")