In [1]:
import pandas as pd
import numpy as np

In [22]:
# 2019_03

df2019_03 = pd.read_csv("./유동인구/FLT_SEOUL_03MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_03["군구"].unique())
days = list(df2019_03["일자"].unique())

for idx in range(len(df2019_03)):
    df2019_03[df2019_03["군구"]]


use_dict_2019_03 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_03[(df2019_03["일자"] == day) & (df2019_03["군구"] == gu)]["유동인구수"])
        use_dict_2019_03["일자"].append(day); use_dict_2019_03["군구"].append(gu); use_dict_2019_03["유동인구수"].append(people)
        
        
people_2019_03 = pd.DataFrame(use_dict_2019_03)

In [27]:
df2019_04

              일자  시간(1시간단위)  연령대(10세단위)  성별   시    군구  유동인구수
0       20190401          0          20  남성  서울   강남구  37650
1       20190401          0          20  남성  서울   동작구  34720
2       20190401          0          20  남성  서울  영등포구  28730
3       20190401          0          20  남성  서울   은평구  28860
4       20190401          0          20  여성  서울   강남구  40420
...          ...        ...         ...  ..  ..   ...    ...
215995  20190430         23          60  여성  서울   도봉구  18570
215996  20190430         23          70  남성  서울   강북구  13290
215997  20190430         23          70  여성  서울   강북구  18310
215998  20190430         23          70  여성  서울   구로구  18160
215999  20190430         23          70  여성  서울   성북구  22580

[216000 rows x 7 columns]

In [28]:
# 2019_04

df2019_04 = pd.read_csv("./유동인구/FLT_SEOUL_04MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_04["군구"].unique())
days = list(df2019_04["일자"].unique())

use_dict_2019_04 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_04[(df2019_04["일자"] == day) & (df2019_04["군구"] == gu)]["유동인구수"])
        use_dict_2019_04["일자"].append(day); use_dict_2019_04["군구"].append(gu); use_dict_2019_04["유동인구수"].append(people)
        
        
people_2019_04 = pd.DataFrame(use_dict_2019_04)

In [30]:
# 2019_05

df2019_05 = pd.read_csv("./유동인구/FLT_SEOUL_05MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_05["군구"].unique())
days = list(df2019_05["일자"].unique())


use_dict_2019_05 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_05[(df2019_05["일자"] == day) & (df2019_05["군구"] == gu)]["유동인구수"])
        use_dict_2019_05["일자"].append(day); use_dict_2019_05["군구"].append(gu); use_dict_2019_05["유동인구수"].append(people)
        
        
people_2019_05 = pd.DataFrame(use_dict_2019_05)

In [31]:
# 2019_06

df2019_06 = pd.read_csv("./유동인구/FLT_SEOUL_06MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_06["군구"].unique())
days = list(df2019_06["일자"].unique())

use_dict_2019_06 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_06[(df2019_06["일자"] == day) & (df2019_06["군구"] == gu)]["유동인구수"])
        use_dict_2019_06["일자"].append(day); use_dict_2019_06["군구"].append(gu); use_dict_2019_06["유동인구수"].append(people)
        
        
people_2019_06 = pd.DataFrame(use_dict_2019_06)

In [33]:
# 2019_07

df2019_07 = pd.read_csv("./유동인구/FLT_SEOUL_07MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_07["군구"].unique())
days = list(df2019_07["일자"].unique())

use_dict_2019_07 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_07[(df2019_07["일자"] == day) & (df2019_07["군구"] == gu)]["유동인구수"])
        use_dict_2019_07["일자"].append(day); use_dict_2019_07["군구"].append(gu); use_dict_2019_07["유동인구수"].append(people)
        
        
people_2019_07 = pd.DataFrame(use_dict_2019_07)

In [34]:
# 2019_08

df2019_08 = pd.read_csv("./유동인구/FLT_SEOUL_08MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_08["군구"].unique())
days = list(df2019_08["일자"].unique())

use_dict_2019_08 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_08[(df2019_08["일자"] == day) & (df2019_08["군구"] == gu)]["유동인구수"])
        use_dict_2019_08["일자"].append(day); use_dict_2019_08["군구"].append(gu); use_dict_2019_08["유동인구수"].append(people)
        
        
people_2019_08 = pd.DataFrame(use_dict_2019_08)

In [35]:
# 2019_09

df2019_09 = pd.read_csv("./유동인구/FLT_SEOUL_09MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_09["군구"].unique())
days = list(df2019_09["일자"].unique())

use_dict_2019_09 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_09[(df2019_09["일자"] == day) & (df2019_09["군구"] == gu)]["유동인구수"])
        use_dict_2019_09["일자"].append(day); use_dict_2019_09["군구"].append(gu); use_dict_2019_09["유동인구수"].append(people)
        
        
people_2019_09 = pd.DataFrame(use_dict_2019_09)

In [36]:
# 2019_10

df2019_10 = pd.read_csv("./유동인구/FLT_SEOUL_10MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_10["군구"].unique())
days = list(df2019_10["일자"].unique())

use_dict_2019_10 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_10[(df2019_10["일자"] == day) & (df2019_10["군구"] == gu)]["유동인구수"])
        use_dict_2019_10["일자"].append(day); use_dict_2019_10["군구"].append(gu); use_dict_2019_10["유동인구수"].append(people)
        
        
people_2019_10 = pd.DataFrame(use_dict_2019_10)

In [37]:
# 2019_11

df2019_11 = pd.read_csv("./유동인구/FLT_SEOUL_11MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_11["군구"].unique())
days = list(df2019_11["일자"].unique())

use_dict_2019_11 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_11[(df2019_11["일자"] == day) & (df2019_11["군구"] == gu)]["유동인구수"])
        use_dict_2019_11["일자"].append(day); use_dict_2019_11["군구"].append(gu); use_dict_2019_11["유동인구수"].append(people)
        
        
people_2019_11 = pd.DataFrame(use_dict_2019_11)

In [38]:
# 2019_12

df2019_12 = pd.read_csv("./유동인구/FLT_SEOUL_12MONTH.csv", encoding = "utf-8")

gu_lst = list(df2019_12["군구"].unique())
days = list(df2019_12["일자"].unique())

use_dict_2019_12 = {"일자" :[], "군구":[], "유동인구수":[]}


for day in days:
    for gu in gu_lst:
        people = sum(df2019_12[(df2019_12["일자"] == day) & (df2019_12["군구"] == gu)]["유동인구수"])
        use_dict_2019_12["일자"].append(day); use_dict_2019_12["군구"].append(gu); use_dict_2019_12["유동인구수"].append(people)
        
        
people_2019_12 = pd.DataFrame(use_dict_2019_12)

In [40]:
move_people = pd.concat([people_2019_03, people_2019_04, people_2019_05, people_2019_06, people_2019_07,
          people_2019_08, people_2019_09, people_2019_10, people_2019_11, people_2019_12]).reset_index(drop = True)

In [42]:
move_people.to_csv("./유동인구/19_03_12_유동인구.csv", encoding = "euc-kr", index = True)